tap "homebrew/cask-fonts"

brew "coreutils"
brew "curl"
brew "dirennv"
brew "erdtree"
brew "fd"
brew "git"
brew "git-lfs"
brew "gnu-sed"
brew "go"
brew "golangci-lint"
brew "htop"
brew "jq"
brew "neovim", args: ["HEAD"]
brew "ripgrep"
brew "rsync"
brew "ssh-copy-id"
brew "unrar"
brew "watch"
brew "wget"
brew "xdelta"

cask "1password-cli"
cask "font-fira-code-nerd-font"
cask "font-hack-nerd-font"
cask "kitty"
